#ifndef CBINDGEN_CYTHON
// This file is generated by cbindgen. DO NOT EDIT
#endif


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void root(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifndef CBINDGEN_CYTHON
/* This is a simple test to ensure that trailers dont cause extra newlines in files */
#endif
