/*
 *  This file is generated by cbindgen. DO NOT EDIT
 */

import com.sun.jna.*;
import com.sun.jna.ptr.*;

enum BindingsSingleton {
  INSTANCE;
  final Bindings lib = Native.load("", Bindings.class);
}

interface Bindings extends Library {
  Bindings INSTANCE = BindingsSingleton.INSTANCE.lib;

  void root();

}
/*
 * This is a simple test to ensure that trailers do not cause extra newlines in files
 */
