#ifndef CBINDGEN_CYTHON
// This file is generated by cbindgen. DO NOT EDIT
#endif


void root(void);

#ifndef CBINDGEN_CYTHON
/* This is a simple test to ensure that trailers dont cause extra newlines in files */
#endif
