/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::fs::File;
use std::io;
use std::io::Read;
use std::path::Path;

use toml;

#[derive(Debug)]
/// Possible errors that can occur during Cargo.toml parsing.
pub enum Error {
    /// Error during reading of Cargo.toml
    Io(io::Error),
    /// Deserialization error
    Toml(toml::de::Error),
}

impl From<io::Error> for Error {
    fn from(err: io::Error) -> Self {
        Error::Io(err)
    }
}
impl From<toml::de::Error> for Error {
    fn from(err: toml::de::Error) -> Self {
        Error::Toml(err)
    }
}

// Warning: Do not change this without regenerating serde_derive impls.
// See issue #203 and README.serde_derive for more information.
#[derive(Clone, Debug)]
pub struct Manifest {
    pub package: Package,
}

// Warning: Do not change this without regenerating serde_derive impls.
// See issue #203 and README.serde_derive for more information.
#[derive(Clone, Debug)]
pub struct Package {
    pub name: String,
}

/// Parse the Cargo.toml for a given path
pub fn manifest(manifest_path: &Path) -> Result<Manifest, Error> {
    let mut s = String::new();
    let mut f = File::open(manifest_path)?;
    f.read_to_string(&mut s)?;

    toml::from_str::<Manifest>(&s).map_err(|x| x.into())
}

// Warning: The following code is autogenerated by serde_derive, don't touch
// unless you know what you're doing. See issue #203 and README.serde_derive
// for more information.

// Generated from `serde_derive 1.80.0`

#[cfg_attr(rustfmt, rustfmt_skip)]
#[allow(non_upper_case_globals,
        unused_attributes,
        unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_Manifest: () =
    {
        #[allow(unknown_lints)]
        #[allow(rust_2018_idioms)]
        extern crate serde as _serde;
        #[allow(unused_macros)]
        macro_rules! try(( $ __expr : expr ) => {
                         match $ __expr {
                         _serde :: export :: Ok ( __val ) => __val
                         , _serde :: export :: Err ( __err ) => {
                         return _serde :: export :: Err ( __err )
                         ; } } });
        #[automatically_derived]
        impl <'de> _serde::Deserialize<'de> for Manifest {
            fn deserialize<__D>(__deserializer: __D)
             -> _serde::export::Result<Self, __D::Error> where
             __D: _serde::Deserializer<'de> {
                #[allow(non_camel_case_types)]
                enum __Field { __field0, __ignore, }
                struct __FieldVisitor;
                impl <'de> _serde::de::Visitor<'de> for
                 __FieldVisitor {
                    type
                    Value
                    =
                    __Field;
                    fn expecting(&self,
                                 __formatter:
                                     &mut _serde::export::Formatter)
                     -> _serde::export::fmt::Result {
                        _serde::export::Formatter::write_str(__formatter,
                                                             "field identifier")
                    }
                    fn visit_u64<__E>(self, __value: u64)
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            0u64 =>
                            _serde::export::Ok(__Field::__field0),
                            _ =>
                            _serde::export::Err(_serde::de::Error::invalid_value(_serde::de::Unexpected::Unsigned(__value),
                                                                                 &"field index 0 <= i < 1")),
                        }
                    }
                    fn visit_str<__E>(self, __value: &str)
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            "package" =>
                            _serde::export::Ok(__Field::__field0),
                            _ => {
                                _serde::export::Ok(__Field::__ignore)
                            }
                        }
                    }
                    fn visit_bytes<__E>(self, __value: &[u8])
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            b"package" =>
                            _serde::export::Ok(__Field::__field0),
                            _ => {
                                _serde::export::Ok(__Field::__ignore)
                            }
                        }
                    }
                }
                impl <'de> _serde::Deserialize<'de> for __Field {
                    #[inline]
                    fn deserialize<__D>(__deserializer: __D)
                     -> _serde::export::Result<Self, __D::Error>
                     where __D: _serde::Deserializer<'de> {
                        _serde::Deserializer::deserialize_identifier(__deserializer,
                                                                     __FieldVisitor)
                    }
                }
                struct __Visitor<'de> {
                    marker: _serde::export::PhantomData<Manifest>,
                    lifetime: _serde::export::PhantomData<&'de ()>,
                }
                impl <'de> _serde::de::Visitor<'de> for
                 __Visitor<'de> {
                    type
                    Value
                    =
                    Manifest;
                    fn expecting(&self,
                                 __formatter:
                                     &mut _serde::export::Formatter)
                     -> _serde::export::fmt::Result {
                        _serde::export::Formatter::write_str(__formatter,
                                                             "struct Manifest")
                    }
                    #[inline]
                    fn visit_seq<__A>(self, mut __seq: __A)
                     ->
                         _serde::export::Result<Self::Value,
                                                __A::Error> where
                     __A: _serde::de::SeqAccess<'de> {
                        let __field0 =
                            match match _serde::de::SeqAccess::next_element::<Package>(&mut __seq)
                                      {
                                      _serde::export::Ok(__val) =>
                                      __val,
                                      _serde::export::Err(__err)
                                      => {
                                          return _serde::export::Err(__err);
                                      }
                                  } {
                                _serde::export::Some(__value) =>
                                __value,
                                _serde::export::None => {
                                    return _serde::export::Err(_serde::de::Error::invalid_length(0usize,
                                                                                                 &"struct Manifest with 1 element"));
                                }
                            };
                        _serde::export::Ok(Manifest{package:
                                                        __field0,})
                    }
                    #[inline]
                    fn visit_map<__A>(self, mut __map: __A)
                     ->
                         _serde::export::Result<Self::Value,
                                                __A::Error> where
                     __A: _serde::de::MapAccess<'de> {
                        let mut __field0:
                                _serde::export::Option<Package> =
                            _serde::export::None;
                        while let _serde::export::Some(__key) =
                                  match _serde::de::MapAccess::next_key::<__Field>(&mut __map)
                                      {
                                      _serde::export::Ok(__val) =>
                                      __val,
                                      _serde::export::Err(__err)
                                      => {
                                          return _serde::export::Err(__err);
                                      }
                                  } {
                            match __key {
                                __Field::__field0 => {
                                    if _serde::export::Option::is_some(&__field0)
                                       {
                                        return _serde::export::Err(<__A::Error
                                                                       as
                                                                       _serde::de::Error>::duplicate_field("package"));
                                    }
                                    __field0 =
                                        _serde::export::Some(match _serde::de::MapAccess::next_value::<Package>(&mut __map)
                                                                 {
                                                                 _serde::export::Ok(__val)
                                                                 =>
                                                                 __val,
                                                                 _serde::export::Err(__err)
                                                                 =>
                                                                 {
                                                                     return _serde::export::Err(__err);
                                                                 }
                                                             });
                                }
                                _ => {
                                    let _ =
                                        match _serde::de::MapAccess::next_value::<_serde::de::IgnoredAny>(&mut __map)
                                            {
                                            _serde::export::Ok(__val)
                                            => __val,
                                            _serde::export::Err(__err)
                                            => {
                                                return _serde::export::Err(__err);
                                            }
                                        };
                                }
                            }
                        }
                        let __field0 =
                            match __field0 {
                                _serde::export::Some(__field0) =>
                                __field0,
                                _serde::export::None =>
                                match _serde::private::de::missing_field("package")
                                    {
                                    _serde::export::Ok(__val) =>
                                    __val,
                                    _serde::export::Err(__err) =>
                                    {
                                        return _serde::export::Err(__err);
                                    }
                                },
                            };
                        _serde::export::Ok(Manifest{package:
                                                        __field0,})
                    }
                }
                const FIELDS: &'static [&'static str] =
                    &["package"];
                _serde::Deserializer::deserialize_struct(__deserializer,
                                                         "Manifest",
                                                         FIELDS,
                                                         __Visitor{marker:
                                                                       _serde::export::PhantomData::<Manifest>,
                                                                   lifetime:
                                                                       _serde::export::PhantomData,})
            }
        }
    };

#[cfg_attr(rustfmt, rustfmt_skip)]
#[allow(non_upper_case_globals,
        unused_attributes,
        unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_Package: () =
    {
        #[allow(unknown_lints)]
        #[allow(rust_2018_idioms)]
        extern crate serde as _serde;
        #[allow(unused_macros)]
        macro_rules! try(( $ __expr : expr ) => {
                         match $ __expr {
                         _serde :: export :: Ok ( __val ) => __val
                         , _serde :: export :: Err ( __err ) => {
                         return _serde :: export :: Err ( __err )
                         ; } } });
        #[automatically_derived]
        impl <'de> _serde::Deserialize<'de> for Package {
            fn deserialize<__D>(__deserializer: __D)
             -> _serde::export::Result<Self, __D::Error> where
             __D: _serde::Deserializer<'de> {
                #[allow(non_camel_case_types)]
                enum __Field { __field0, __ignore, }
                struct __FieldVisitor;
                impl <'de> _serde::de::Visitor<'de> for
                 __FieldVisitor {
                    type
                    Value
                    =
                    __Field;
                    fn expecting(&self,
                                 __formatter:
                                     &mut _serde::export::Formatter)
                     -> _serde::export::fmt::Result {
                        _serde::export::Formatter::write_str(__formatter,
                                                             "field identifier")
                    }
                    fn visit_u64<__E>(self, __value: u64)
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            0u64 =>
                            _serde::export::Ok(__Field::__field0),
                            _ =>
                            _serde::export::Err(_serde::de::Error::invalid_value(_serde::de::Unexpected::Unsigned(__value),
                                                                                 &"field index 0 <= i < 1")),
                        }
                    }
                    fn visit_str<__E>(self, __value: &str)
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            "name" =>
                            _serde::export::Ok(__Field::__field0),
                            _ => {
                                _serde::export::Ok(__Field::__ignore)
                            }
                        }
                    }
                    fn visit_bytes<__E>(self, __value: &[u8])
                     -> _serde::export::Result<Self::Value, __E>
                     where __E: _serde::de::Error {
                        match __value {
                            b"name" =>
                            _serde::export::Ok(__Field::__field0),
                            _ => {
                                _serde::export::Ok(__Field::__ignore)
                            }
                        }
                    }
                }
                impl <'de> _serde::Deserialize<'de> for __Field {
                    #[inline]
                    fn deserialize<__D>(__deserializer: __D)
                     -> _serde::export::Result<Self, __D::Error>
                     where __D: _serde::Deserializer<'de> {
                        _serde::Deserializer::deserialize_identifier(__deserializer,
                                                                     __FieldVisitor)
                    }
                }
                struct __Visitor<'de> {
                    marker: _serde::export::PhantomData<Package>,
                    lifetime: _serde::export::PhantomData<&'de ()>,
                }
                impl <'de> _serde::de::Visitor<'de> for
                 __Visitor<'de> {
                    type
                    Value
                    =
                    Package;
                    fn expecting(&self,
                                 __formatter:
                                     &mut _serde::export::Formatter)
                     -> _serde::export::fmt::Result {
                        _serde::export::Formatter::write_str(__formatter,
                                                             "struct Package")
                    }
                    #[inline]
                    fn visit_seq<__A>(self, mut __seq: __A)
                     ->
                         _serde::export::Result<Self::Value,
                                                __A::Error> where
                     __A: _serde::de::SeqAccess<'de> {
                        let __field0 =
                            match match _serde::de::SeqAccess::next_element::<String>(&mut __seq)
                                      {
                                      _serde::export::Ok(__val) =>
                                      __val,
                                      _serde::export::Err(__err)
                                      => {
                                          return _serde::export::Err(__err);
                                      }
                                  } {
                                _serde::export::Some(__value) =>
                                __value,
                                _serde::export::None => {
                                    return _serde::export::Err(_serde::de::Error::invalid_length(0usize,
                                                                                                 &"struct Package with 1 element"));
                                }
                            };
                        _serde::export::Ok(Package{name:
                                                       __field0,})
                    }
                    #[inline]
                    fn visit_map<__A>(self, mut __map: __A)
                     ->
                         _serde::export::Result<Self::Value,
                                                __A::Error> where
                     __A: _serde::de::MapAccess<'de> {
                        let mut __field0:
                                _serde::export::Option<String> =
                            _serde::export::None;
                        while let _serde::export::Some(__key) =
                                  match _serde::de::MapAccess::next_key::<__Field>(&mut __map)
                                      {
                                      _serde::export::Ok(__val) =>
                                      __val,
                                      _serde::export::Err(__err)
                                      => {
                                          return _serde::export::Err(__err);
                                      }
                                  } {
                            match __key {
                                __Field::__field0 => {
                                    if _serde::export::Option::is_some(&__field0)
                                       {
                                        return _serde::export::Err(<__A::Error
                                                                       as
                                                                       _serde::de::Error>::duplicate_field("name"));
                                    }
                                    __field0 =
                                        _serde::export::Some(match _serde::de::MapAccess::next_value::<String>(&mut __map)
                                                                 {
                                                                 _serde::export::Ok(__val)
                                                                 =>
                                                                 __val,
                                                                 _serde::export::Err(__err)
                                                                 =>
                                                                 {
                                                                     return _serde::export::Err(__err);
                                                                 }
                                                             });
                                }
                                _ => {
                                    let _ =
                                        match _serde::de::MapAccess::next_value::<_serde::de::IgnoredAny>(&mut __map)
                                            {
                                            _serde::export::Ok(__val)
                                            => __val,
                                            _serde::export::Err(__err)
                                            => {
                                                return _serde::export::Err(__err);
                                            }
                                        };
                                }
                            }
                        }
                        let __field0 =
                            match __field0 {
                                _serde::export::Some(__field0) =>
                                __field0,
                                _serde::export::None =>
                                match _serde::private::de::missing_field("name")
                                    {
                                    _serde::export::Ok(__val) =>
                                    __val,
                                    _serde::export::Err(__err) =>
                                    {
                                        return _serde::export::Err(__err);
                                    }
                                },
                            };
                        _serde::export::Ok(Package{name:
                                                       __field0,})
                    }
                }
                const FIELDS: &'static [&'static str] = &["name"];
                _serde::Deserializer::deserialize_struct(__deserializer,
                                                         "Package",
                                                         FIELDS,
                                                         __Visitor{marker:
                                                                       _serde::export::PhantomData::<Package>,
                                                                   lifetime:
                                                                       _serde::export::PhantomData,})
            }
        }
    };
